from pygame.locals import *

GAME_TITLE = 'Tetris'

# Board constants
BOARD_WIDTH = 12
BOARD_HEIGHT = 22
BOARD_OFFSET_X = 32
BOARD_OFFSET_Y = 32
BLOCK_PIXELS = 32
INFO_PANEL_WIDTH = 300

# speed
BLOCK_SPEED = 500  # Speed blocks fall in milliseconds
KEY_REPEAT = 150  # Key repeat in milliseconds
# Block colours
EMPTY = 0
RED = 1
GREEN = 2
BLUE = 3
YELLOW = 4
MAGENTA = 5
CYAN = 6
GREY = 7

BLOCK_COLOURS = [RED, GREEN, BLUE, YELLOW, MAGENTA, CYAN]

# Shape Types
SQUARE = 1
BAR = 2
LEFT_L = 3
RIGHT_L = 4
LEFT_STEP = 5
RIGHT_STEP = 6

SHAPE_TYPES = [SQUARE, BAR, LEFT_L, RIGHT_L, LEFT_STEP, RIGHT_STEP]
# Player states
DEAD = 0
ALIVE = 1

# Game states
MENU = 0
PLAYING = 1
PAUSED = 2
GAME_OVER = 3

# Game events
BLOCK_DOWN_EVENT = USEREVENT + 1
ROWS_COMPLETE_EVENT = USEREVENT + 2
